[package]
name = "bevy_define"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
bevy_ecs = { version = "0.19", features = ["bevy_reflect", "debug"] }
bevy_ptr = "0.19"
bevy_platform = "0.19"
bevy_utils = "0.19"
bevy_reflect = "0.19"
variadics_please = { version = "1.1.0" }

#[lints]
#workspace = true
